<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <?php include '../seo.php';?>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Roth Architecture - Sfer-Ik Tulum</title>
    <meta name="description" content="Roth Architecture - Sfer-Ik Tulum" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

     <!-- Open Graph-->
          <meta property="og:title" content="Roth Architecture - Sfer-Ik Tulum">
          <meta property="og:description" content="Roth Architecture - Sfer-Ik Tulum"> 
          <meta property="og:site_name" content="Roth Architecture">
          <meta property="og:locale" content="en"> 
          <meta property="og:type" content="website">
          <meta property="og:url" content="https://roth-architecture.com">
          <meta property="og:image" content=<?php echo ($dire."images/proyectos/og/og--sfer-ik-tulum.webp")?>> 
          <link rel="canonical" href="https://roth-architecture.com/" />
        <!-- <link rel="manifest" href="site.webmanifest"> --> 
        <link rel="apple-touch-icon" href=<?php echo ($dire."icon.png")?>>
        <!-- Place favicon.ico in the root directory -->
        <link rel="shortcut icon" href=<?php echo ($dire."images/favicon-black-bg.png")?>>
        <link rel="icon" type="image/png" href=<?php echo ($dire."images/favicon-black-bg.png")?>>

            <link defer rel="stylesheet" href=<?php echo ($dire."css/main.css")?>>
<link rel="stylesheet" href=<?php echo ($dire."css/normalize.css")?>>
		<link rel="stylesheet" type="text/css" href=<?php echo ($dire."css/slick-theme.css")?>>
	  	<link rel="stylesheet" href=<?php echo ($dire."css/slickp.css")?>>
    
        <link defer href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
	  
	  <div class="loading-container">
      <div class="loading-screen">
      </div>
    </div>
		
		    <div data-barba="wrapper">

      <div data-barba="container" data-barba-namespace="sferikt">
		  
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src=https://www.googletagmanager.com/ns.html?id=GTM-PRX75J7
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->	
		  
<?php include '../header.php';?>	

<div id="smooth-wrapper">
<div id="smooth-content">
	<div class="backnav"></div>	  
<div class="bproyect"> 
	  
	  <div class="projects-single-wrap" >
    <section class="sections container-fluid proj-header" 
    style="background-image: url(../images/proyectos/sfer-ik-tulum/sfer-ik-tulum-5.webp);">
  <div class="row">
    <div class="col"> 
  <div class="title">
    <h1 class="h1h vish" >SFER-IK Tulum</h1>
  </div>

    </div>
  </div>
    </section>

    <section class="sections container-fluid proj-ficha ">
        <div class="row w-75 mx-auto">
          <div class="col"> 
<div class="fichatec">
            <div class="fichatec-item">Type: <b> Cultural</b></div>
            <div class="fichatec-item">Location: <b>Tulum</b></div>
            <div class="fichatec-item">Size: <b>490 sqm</b></div>
            <div class="fichatec-item">Status: <b>Completed</b></div>
            <div class="fichatec-item">Year: <b>2017</b></div>
        </div>
          </div>
        </div>
    </section>

    <section class="sections container first-row" >
        <div class="row g-5 ">
          
           <div class="col-md-6 d-flex align-items-center">
            <div>
                <div class="topheader"> <img alt="dash" class="topheaderi" src="../images/SVG/guion-topheader.svg"> </div>
                <h1 class="pb-2" >SFER-IK Tulum</h1>
                <div class="social-share pb-3">
                    Share: 
                   <div class="sharethis-inline-share-buttons" data-title="Roth Architecture - Sfer-Ik Tulum"></div>
                </div>
            <p data-lag="0.5"
>
                Born as a space for interdisciplinary creation, SFER IK is a museum that defies the conventions of contemplative exercises. Contrary to the traditional way of exhibiting art, where stimuli parallel to the artworks are almost entirely absent, SFER IK is an integral experience where all our senses are active. The natural contour of the ground creates a sinuous journey that takes us literally up and down as we transit through space. Windows act like canvases, while they provide the galleries with natural light and become an additional stimulus to the contrast, both visual and tactile, generated by the concrete and the bejuco.


            </p>
        </div>
           </div>

           <div class="col-md-6">
			   
			   <div class="img-wrapor1 alto80">
            <div class="imgcontor1 contain">
                <img alt="Sfer-Ik Tulum" data-speed="0.5" class="imgzorg1 imgo2" style="visibility: hidden;"  src="../images/proyectos/sfer-ik-tulum/sfer-ik-tulum-1.webp" >
              </div>
					</div>
			 
			   
			   
			   
           </div>
        </div>
    </section>

       

    

   <section class="sections container-fluid  ">
        <div class="row" style="position:relative;">

                <div class="img-wrap-cover-fullw  imghlg">
                    <img alt="Sfer-Ik Tulum" src="../images/proyectos/sfer-ik-tulum/sfer-ik-tulum-2.webp" >
                  </div>
			
  
        </div>
    </section>



    <section class="sections container mb-4">
        <div class="row g-5">
            <div class="col-md-6 ">
               <div class="img-wrapor1 alto80">
            <div class="imgcontor1 contain">
                <img alt="Sfer-Ik Tulum" data-speed="0.5" class="imgzorg1 imgo2" style="visibility: hidden;"  src="../images/proyectos/sfer-ik-tulum/sfer-ik-tulum-3.webp" >
              </div>
					</div>
            </div>
            <div class="col-md-6 " >
                 <div class="img-wrapor1 alto80">
            <div class="imgcontor1 contain">
                <img alt="Sfer-Ik Tulum" data-speed="0.5" class="imgzorg1 imgo2" style="visibility: hidden;"  src="../images/proyectos/sfer-ik-tulum/sfer-ik-tulum-4.webp" >
              </div>
					</div>
              </div>
          </div>
    </section>



    <!--Related post-->
    <section class="sections container-fluid related-post">
        <div class="container ">
     <div class="row g-5">
        <h2 class="pt-5 text-center">Related Projects</h2>
            <div class="col-md-4 ">
              
				 <a href="sfer-ik-uh-may.php" class="extpost botper">
              <div class="img-wrap-cover1 imghproygrid-related ">
            <img alt="Sfer-Ik Tulum" src="../images/proyectos/sfer-ik-uh-may/sfer-ik-uh-mau-6.webp" >
				   <div class="tab-text">
					   <h2>SFER-IK Uh May</h2>
                  </div>
          </div>
				  </a>
				
				
				
        </div>
        <div class="col-md-4 ">
            
			
			<a href="tseen-ja.php" class="extpost botper">
              <div class="img-wrap-cover1 imghproygrid-related ">
            <img alt="Sfer-Ik Tulum" src="../images/proyectos/tseen-ja/tseen-ja-3.webp" >
				   <div class="tab-text">
					   <h2>Tseen Ja</h2>
                  </div>
          </div>
				  </a>
			
			
    </div>
    <div class="col-md-4 ">
      
		  <a href="zak-ik.php" class="extpost botper">
              <div class="img-wrap-cover1 imghproygrid-related ">
            <img alt="Sfer-Ik Tulum" src="../images/proyectos/zak-ik/zak-ik-8.webp" >
				   <div class="tab-text">
					   <h2>Zak Ik</h2>
                  </div>
          </div>
				  </a>
		
		
</div>
          </div>
        </div>
    </section>
   
   </div> 
	
		 
<?php include '../footer.php';?>
</div>	
	</div>
</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
		
    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js" integrity="sha256-dHf/YjH1A4tewEsKUSmNnV05DDbfGN3g7NMq86xgGh8=" crossorigin="anonymous"></script>
		<script src="https://unpkg.com/@barba/core"></script>
<script src="https://unpkg.com/@barba/prefetch"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollTrigger.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/Observer.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollToPlugin.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.8.3/TweenMax.min.js"></script>
		<script src=<?php echo ($dire."js/DrawSVGPlugin.min.js")?>></script>	
		<script src=<?php echo ($dire."js/SplitText.min.js")?>></script>
		<script src=<?php echo ($dire."js/ScrollSmoother.min.js")?>></script>
		<script src=<?php echo ($dire."js/slick.js")?>></script>
		<script src=<?php echo ($dire."js/interior.js")?>></script>
		<script src=<?php echo ($dire."js/main.js")?>></script>
<script src="https://platform-api.sharethis.com/js/sharethis.js#property=63a60f2f65735e001232db71&product=sop" asinc defer></script>

  </body>
</html>
